### PR TITLE
Update variables.tf

### PR DESCRIPTION
**Pull request by nthacks**
Fix typo in "ocid" and update map based on latest details in https://docs.cloud.oracle.com/en-us/iaas/images/image/cc81a889-bc7f-4b70-b8e7-0503812665be/

### CODE REVIEW

**Comment by mjtechguy** [comment]
reviewing this later today

**Comment by nthacks** [comment]
One might also consider updating them based on the latest available Ubuntu image.

**Comment by rob151515** [comment]
I had an error while trying this and I think it was due to removing a close '}' that was required?

**Comment by mjtechguy** [comment]
@rob151515 can you point to where it appears to be missing? 

Feel free to submit a PR.

Thanks!

MJ

**Comment by rob151515** [comment]
the variable "instance_image_ocid" seems to be missing a closing '}'.

Sorry very new to GitHub so not sure about a PR.

Cheers.

**Comment by mjtechguy** [comment]
Thanks @rob151515 should be fixed now. Appreciate you pointing that out!

**Pull request merged**
